const CATEGORIES = [
  { id: 'all', label: 'ぜんぶ' },
  { id: 'shizen', label: 'しぜん' },
  { id: 'karada', label: 'からだ・ひと' },
  { id: 'dousa', label: 'どうさ' },
  { id: 'gakkou', label: 'がっこう' },
  { id: 'basho', label: 'ばしょ' },
  { id: 'jikan', label: 'じかん' },
  { id: 'kazu', label: 'かず・かたち' },
  { id: 'sonota', label: 'その他' },
];

const KANJI_DATA = [
  // === しぜん (nature) ===
  { char: '羽', on: 'ウ', kun: 'は・はね', strokes: 6, category: 'shizen', example: '羽（はね）' },
  { char: '雲', on: 'ウン', kun: 'くも', strokes: 12, category: 'shizen', example: '雲（くも）' },
  { char: '海', on: 'カイ', kun: 'うみ', strokes: 9, category: 'shizen', example: '海（うみ）' },
  { char: '岩', on: 'ガン', kun: 'いわ', strokes: 8, category: 'shizen', example: '岩（いわ）' },
  { char: '牛', on: 'ギュウ', kun: 'うし', strokes: 4, category: 'shizen', example: '牛（うし）' },
  { char: '魚', on: 'ギョ', kun: 'うお・さかな', strokes: 11, category: 'shizen', example: '魚（さかな）' },
  { char: '原', on: 'ゲン', kun: 'はら', strokes: 10, category: 'shizen', example: '原っぱ（はらっぱ）' },
  { char: '光', on: 'コウ', kun: 'ひか(る)', strokes: 6, category: 'shizen', example: '光（ひかり）' },
  { char: '黄', on: 'コウ・オウ', kun: 'き・こ', strokes: 11, category: 'shizen', example: '黄色（きいろ）' },
  { char: '黒', on: 'コク', kun: 'くろ・くろ(い)', strokes: 11, category: 'shizen', example: '黒い（くろい）' },
  { char: '谷', on: 'コク', kun: 'たに', strokes: 7, category: 'shizen', example: '谷（たに）' },
  { char: '秋', on: 'シュウ', kun: 'あき', strokes: 9, category: 'shizen', example: '秋（あき）' },
  { char: '春', on: 'シュン', kun: 'はる', strokes: 9, category: 'shizen', example: '春（はる）' },
  { char: '色', on: 'ショク・シキ', kun: 'いろ', strokes: 6, category: 'shizen', example: '色（いろ）' },
  { char: '晴', on: 'セイ', kun: 'は(れる)', strokes: 12, category: 'shizen', example: '晴れ（はれ）' },
  { char: '雪', on: 'セツ', kun: 'ゆき', strokes: 11, category: 'shizen', example: '雪（ゆき）' },
  { char: '星', on: 'セイ', kun: 'ほし', strokes: 9, category: 'shizen', example: '星（ほし）' },
  { char: '池', on: 'チ', kun: 'いけ', strokes: 6, category: 'shizen', example: '池（いけ）' },
  { char: '鳥', on: 'チョウ', kun: 'とり', strokes: 11, category: 'shizen', example: '鳥（とり）' },
  { char: '冬', on: 'トウ', kun: 'ふゆ', strokes: 5, category: 'shizen', example: '冬（ふゆ）' },
  { char: '夏', on: 'カ', kun: 'なつ', strokes: 10, category: 'shizen', example: '夏（なつ）' },
  { char: '馬', on: 'バ', kun: 'うま・ま', strokes: 10, category: 'shizen', example: '馬（うま）' },
  { char: '麦', on: 'バク', kun: 'むぎ', strokes: 7, category: 'shizen', example: '麦（むぎ）' },
  { char: '風', on: 'フウ・フ', kun: 'かぜ・かざ', strokes: 9, category: 'shizen', example: '風（かぜ）' },
  { char: '米', on: 'ベイ・マイ', kun: 'こめ', strokes: 6, category: 'shizen', example: '米（こめ）' },
  { char: '毛', on: 'モウ', kun: 'け', strokes: 4, category: 'shizen', example: '毛（け）' },
  { char: '野', on: 'ヤ', kun: 'の', strokes: 11, category: 'shizen', example: '野原（のはら）' },
  { char: '茶', on: 'チャ・サ', kun: '', strokes: 9, category: 'shizen', example: 'お茶（おちゃ）' },

  // === からだ・ひと (body/people) ===
  { char: '顔', on: 'ガン', kun: 'かお', strokes: 18, category: 'karada', example: '顔（かお）' },
  { char: '兄', on: 'ケイ・キョウ', kun: 'あに', strokes: 5, category: 'karada', example: 'お兄さん（おにいさん）' },
  { char: '首', on: 'シュ', kun: 'くび', strokes: 9, category: 'karada', example: '首（くび）' },
  { char: '心', on: 'シン', kun: 'こころ', strokes: 4, category: 'karada', example: '心（こころ）' },
  { char: '親', on: 'シン', kun: 'おや・した(しい)', strokes: 16, category: 'karada', example: '親（おや）' },
  { char: '体', on: 'タイ・テイ', kun: 'からだ', strokes: 7, category: 'karada', example: '体（からだ）' },
  { char: '弟', on: 'テイ・ダイ', kun: 'おとうと', strokes: 7, category: 'karada', example: '弟（おとうと）' },
  { char: '頭', on: 'トウ・ズ', kun: 'あたま', strokes: 16, category: 'karada', example: '頭（あたま）' },
  { char: '肉', on: 'ニク', kun: '', strokes: 6, category: 'karada', example: '肉（にく）' },
  { char: '父', on: 'フ', kun: 'ちち', strokes: 4, category: 'karada', example: 'お父さん（おとうさん）' },
  { char: '母', on: 'ボ', kun: 'はは', strokes: 5, category: 'karada', example: 'お母さん（おかあさん）' },
  { char: '妹', on: 'マイ', kun: 'いもうと', strokes: 8, category: 'karada', example: '妹（いもうと）' },
  { char: '姉', on: 'シ', kun: 'あね', strokes: 8, category: 'karada', example: 'お姉さん（おねえさん）' },
  { char: '声', on: 'セイ・ショウ', kun: 'こえ', strokes: 7, category: 'karada', example: '声（こえ）' },
  { char: '友', on: 'ユウ', kun: 'とも', strokes: 4, category: 'karada', example: '友だち（ともだち）' },

  // === どうさ (actions/verbs) ===
  { char: '引', on: 'イン', kun: 'ひ(く)', strokes: 4, category: 'dousa', example: '引く（ひく）' },
  { char: '歌', on: 'カ', kun: 'うた・うた(う)', strokes: 14, category: 'dousa', example: '歌う（うたう）' },
  { char: '回', on: 'カイ・エ', kun: 'まわ(る)', strokes: 6, category: 'dousa', example: '回る（まわる）' },
  { char: '会', on: 'カイ・エ', kun: 'あ(う)', strokes: 6, category: 'dousa', example: '会う（あう）' },
  { char: '活', on: 'カツ', kun: '', strokes: 9, category: 'dousa', example: '生活（せいかつ）' },
  { char: '帰', on: 'キ', kun: 'かえ(る)', strokes: 10, category: 'dousa', example: '帰る（かえる）' },
  { char: '強', on: 'キョウ・ゴウ', kun: 'つよ(い)', strokes: 11, category: 'dousa', example: '強い（つよい）' },
  { char: '教', on: 'キョウ', kun: 'おし(える)', strokes: 11, category: 'dousa', example: '教える（おしえる）' },
  { char: '言', on: 'ゲン・ゴン', kun: 'い(う)・こと', strokes: 7, category: 'dousa', example: '言う（いう）' },
  { char: '考', on: 'コウ', kun: 'かんが(える)', strokes: 6, category: 'dousa', example: '考える（かんがえる）' },
  { char: '行', on: 'コウ・ギョウ', kun: 'い(く)・おこな(う)', strokes: 6, category: 'dousa', example: '行く（いく）' },
  { char: '合', on: 'ゴウ・ガッ・カッ', kun: 'あ(う)', strokes: 6, category: 'dousa', example: '合う（あう）' },
  { char: '作', on: 'サク・サ', kun: 'つく(る)', strokes: 7, category: 'dousa', example: '作る（つくる）' },
  { char: '止', on: 'シ', kun: 'と(まる)', strokes: 4, category: 'dousa', example: '止まる（とまる）' },
  { char: '思', on: 'シ', kun: 'おも(う)', strokes: 9, category: 'dousa', example: '思う（おもう）' },
  { char: '知', on: 'チ', kun: 'し(る)', strokes: 8, category: 'dousa', example: '知る（しる）' },
  { char: '食', on: 'ショク', kun: 'た(べる)', strokes: 9, category: 'dousa', example: '食べる（たべる）' },
  { char: '切', on: 'セツ・サイ', kun: 'き(る)', strokes: 4, category: 'dousa', example: '切る（きる）' },
  { char: '走', on: 'ソウ', kun: 'はし(る)', strokes: 7, category: 'dousa', example: '走る（はしる）' },
  { char: '多', on: 'タ', kun: 'おお(い)', strokes: 6, category: 'dousa', example: '多い（おおい）' },
  { char: '通', on: 'ツウ・ツ', kun: 'とお(る)・かよ(う)', strokes: 10, category: 'dousa', example: '通る（とおる）' },
  { char: '答', on: 'トウ', kun: 'こた(える)', strokes: 12, category: 'dousa', example: '答える（こたえる）' },
  { char: '当', on: 'トウ', kun: 'あ(たる)', strokes: 6, category: 'dousa', example: '当たる（あたる）' },
  { char: '同', on: 'ドウ', kun: 'おな(じ)', strokes: 6, category: 'dousa', example: '同じ（おなじ）' },
  { char: '読', on: 'ドク・トク・トウ', kun: 'よ(む)', strokes: 14, category: 'dousa', example: '読む（よむ）' },
  { char: '売', on: 'バイ', kun: 'う(る)', strokes: 7, category: 'dousa', example: '売る（うる）' },
  { char: '買', on: 'バイ', kun: 'か(う)', strokes: 12, category: 'dousa', example: '買う（かう）' },
  { char: '聞', on: 'ブン・モン', kun: 'き(く)', strokes: 14, category: 'dousa', example: '聞く（きく）' },
  { char: '歩', on: 'ホ・ブ', kun: 'ある(く)・あゆ(む)', strokes: 8, category: 'dousa', example: '歩く（あるく）' },
  { char: '鳴', on: 'メイ', kun: 'な(く)・な(る)', strokes: 14, category: 'dousa', example: '鳴く（なく）' },
  { char: '用', on: 'ヨウ', kun: 'もち(いる)', strokes: 5, category: 'dousa', example: '用いる（もちいる）' },
  { char: '来', on: 'ライ', kun: 'く(る)・きた(る)', strokes: 7, category: 'dousa', example: '来る（くる）' },
  { char: '話', on: 'ワ', kun: 'はな(す)・はなし', strokes: 13, category: 'dousa', example: '話す（はなす）' },
  { char: '交', on: 'コウ', kun: 'まじ(わる)・ま(ぜる)', strokes: 6, category: 'dousa', example: '交わる（まじわる）' },
  { char: '記', on: 'キ', kun: 'しる(す)', strokes: 10, category: 'dousa', example: '記す（しるす）' },
  { char: '計', on: 'ケイ', kun: 'はか(る)', strokes: 9, category: 'dousa', example: '計る（はかる）' },
  { char: '算', on: 'サン', kun: '', strokes: 14, category: 'dousa', example: '算数（さんすう）' },
  { char: '少', on: 'ショウ', kun: 'すく(ない)・すこ(し)', strokes: 4, category: 'dousa', example: '少ない（すくない）' },
  { char: '弱', on: 'ジャク', kun: 'よわ(い)', strokes: 10, category: 'dousa', example: '弱い（よわい）' },
  { char: '直', on: 'チョク・ジキ', kun: 'なお(す)・ただ(ちに)', strokes: 8, category: 'dousa', example: '直す（なおす）' },
  { char: '書', on: 'ショ', kun: 'か(く)', strokes: 10, category: 'dousa', example: '書く（かく）' },

  // === がっこう (school) ===
  { char: '画', on: 'ガ・カク', kun: '', strokes: 8, category: 'gakkou', example: '画用紙（がようし）' },
  { char: '絵', on: 'カイ・エ', kun: '', strokes: 12, category: 'gakkou', example: '絵（え）' },
  { char: '科', on: 'カ', kun: '', strokes: 9, category: 'gakkou', example: '科目（かもく）' },
  { char: '紙', on: 'シ', kun: 'かみ', strokes: 10, category: 'gakkou', example: '紙（かみ）' },
  { char: '図', on: 'ズ・ト', kun: 'はか(る)', strokes: 7, category: 'gakkou', example: '図（ず）' },
  { char: '数', on: 'スウ・ス', kun: 'かず・かぞ(える)', strokes: 13, category: 'gakkou', example: '数（かず）' },
  { char: '線', on: 'セン', kun: '', strokes: 15, category: 'gakkou', example: '線（せん）' },
  { char: '点', on: 'テン', kun: '', strokes: 9, category: 'gakkou', example: '点（てん）' },
  { char: '形', on: 'ケイ・ギョウ', kun: 'かたち・かた', strokes: 7, category: 'gakkou', example: '形（かたち）' },
  { char: '丸', on: 'ガン', kun: 'まる・まる(い)', strokes: 3, category: 'gakkou', example: '丸い（まるい）' },
  { char: '矢', on: 'シ', kun: 'や', strokes: 5, category: 'gakkou', example: '矢（や）' },
  { char: '弓', on: 'キュウ', kun: 'ゆみ', strokes: 3, category: 'gakkou', example: '弓（ゆみ）' },
  { char: '刀', on: 'トウ', kun: 'かたな', strokes: 2, category: 'gakkou', example: '刀（かたな）' },

  // === ばしょ (places) ===
  { char: '園', on: 'エン', kun: 'その', strokes: 13, category: 'basho', example: '公園（こうえん）' },
  { char: '家', on: 'カ・ケ', kun: 'いえ・や', strokes: 10, category: 'basho', example: '家（いえ）' },
  { char: '京', on: 'キョウ・ケイ', kun: '', strokes: 8, category: 'basho', example: '東京（とうきょう）' },
  { char: '国', on: 'コク', kun: 'くに', strokes: 8, category: 'basho', example: '国（くに）' },
  { char: '市', on: 'シ', kun: 'いち', strokes: 5, category: 'basho', example: '市（し）' },
  { char: '寺', on: 'ジ', kun: 'てら', strokes: 6, category: 'basho', example: 'お寺（おてら）' },
  { char: '社', on: 'シャ', kun: 'やしろ', strokes: 7, category: 'basho', example: '神社（じんじゃ）' },
  { char: '室', on: 'シツ', kun: 'むろ', strokes: 9, category: 'basho', example: '教室（きょうしつ）' },
  { char: '場', on: 'ジョウ', kun: 'ば', strokes: 12, category: 'basho', example: '場所（ばしょ）' },
  { char: '台', on: 'ダイ・タイ', kun: '', strokes: 5, category: 'basho', example: '台（だい）' },
  { char: '地', on: 'チ・ジ', kun: '', strokes: 6, category: 'basho', example: '地図（ちず）' },
  { char: '店', on: 'テン', kun: 'みせ', strokes: 8, category: 'basho', example: 'お店（おみせ）' },
  { char: '道', on: 'ドウ', kun: 'みち', strokes: 12, category: 'basho', example: '道（みち）' },
  { char: '門', on: 'モン', kun: 'かど', strokes: 8, category: 'basho', example: '門（もん）' },
  { char: '戸', on: 'コ', kun: 'と', strokes: 4, category: 'basho', example: '戸（と）' },

  // === じかん (time) ===
  { char: '間', on: 'カン・ケン', kun: 'あいだ・ま', strokes: 12, category: 'jikan', example: '時間（じかん）' },
  { char: '時', on: 'ジ', kun: 'とき', strokes: 10, category: 'jikan', example: '時間（じかん）' },
  { char: '朝', on: 'チョウ', kun: 'あさ', strokes: 12, category: 'jikan', example: '朝（あさ）' },
  { char: '昼', on: 'チュウ', kun: 'ひる', strokes: 9, category: 'jikan', example: '昼（ひる）' },
  { char: '夜', on: 'ヤ', kun: 'よ・よる', strokes: 8, category: 'jikan', example: '夜（よる）' },
  { char: '午', on: 'ゴ', kun: '', strokes: 4, category: 'jikan', example: '午前（ごぜん）' },
  { char: '前', on: 'ゼン', kun: 'まえ', strokes: 9, category: 'jikan', example: '前（まえ）' },
  { char: '後', on: 'ゴ・コウ', kun: 'あと・うし(ろ)', strokes: 9, category: 'jikan', example: '午後（ごご）' },
  { char: '曜', on: 'ヨウ', kun: '', strokes: 18, category: 'jikan', example: '曜日（ようび）' },
  { char: '週', on: 'シュウ', kun: '', strokes: 11, category: 'jikan', example: '一週間（いっしゅうかん）' },
  { char: '毎', on: 'マイ', kun: '', strokes: 6, category: 'jikan', example: '毎日（まいにち）' },
  { char: '今', on: 'コン・キン', kun: 'いま', strokes: 4, category: 'jikan', example: '今（いま）' },

  // === かず・かたち (numbers/shapes) ===
  { char: '万', on: 'マン・バン', kun: '', strokes: 3, category: 'kazu', example: '一万（いちまん）' },
  { char: '半', on: 'ハン', kun: 'なか(ば)', strokes: 5, category: 'kazu', example: '半分（はんぶん）' },
  { char: '番', on: 'バン', kun: '', strokes: 12, category: 'kazu', example: '一番（いちばん）' },
  { char: '才', on: 'サイ', kun: '', strokes: 3, category: 'kazu', example: '才（さい）' },
  { char: '元', on: 'ゲン・ガン', kun: 'もと', strokes: 4, category: 'kazu', example: '元気（げんき）' },
  { char: '長', on: 'チョウ', kun: 'なが(い)', strokes: 8, category: 'kazu', example: '長い（ながい）' },
  { char: '細', on: 'サイ', kun: 'ほそ(い)・こま(かい)', strokes: 11, category: 'kazu', example: '細い（ほそい）' },
  { char: '高', on: 'コウ', kun: 'たか(い)', strokes: 10, category: 'kazu', example: '高い（たかい）' },
  { char: '広', on: 'コウ', kun: 'ひろ(い)', strokes: 5, category: 'kazu', example: '広い（ひろい）' },
  { char: '近', on: 'キン', kun: 'ちか(い)', strokes: 7, category: 'kazu', example: '近い（ちかい）' },
  { char: '遠', on: 'エン・オン', kun: 'とお(い)', strokes: 13, category: 'kazu', example: '遠い（とおい）' },
  { char: '太', on: 'タイ・タ', kun: 'ふと(い)', strokes: 4, category: 'kazu', example: '太い（ふとい）' },
  { char: '新', on: 'シン', kun: 'あたら(しい)・あら(た)', strokes: 13, category: 'kazu', example: '新しい（あたらしい）' },
  { char: '古', on: 'コ', kun: 'ふる(い)', strokes: 5, category: 'kazu', example: '古い（ふるい）' },
  { char: '角', on: 'カク', kun: 'かど・つの', strokes: 7, category: 'kazu', example: '角（かど）' },
  { char: '方', on: 'ホウ', kun: 'かた', strokes: 4, category: 'kazu', example: '方（かた）' },
  { char: '内', on: 'ナイ・ダイ', kun: 'うち', strokes: 4, category: 'kazu', example: '内（うち）' },
  { char: '外', on: 'ガイ・ゲ', kun: 'そと・ほか・はず(す)', strokes: 5, category: 'kazu', example: '外（そと）' },

  // === その他 (others) ===
  { char: '何', on: 'カ', kun: 'なに・なん', strokes: 7, category: 'sonota', example: '何（なに）' },
  { char: '楽', on: 'ガク・ラク', kun: 'たの(しい)', strokes: 13, category: 'sonota', example: '楽しい（たのしい）' },
  { char: '汽', on: 'キ', kun: '', strokes: 7, category: 'sonota', example: '汽車（きしゃ）' },
  { char: '語', on: 'ゴ', kun: 'かた(る)', strokes: 14, category: 'sonota', example: '日本語（にほんご）' },
  { char: '工', on: 'コウ・ク', kun: '', strokes: 3, category: 'sonota', example: '工作（こうさく）' },
  { char: '公', on: 'コウ', kun: 'おおやけ', strokes: 4, category: 'sonota', example: '公園（こうえん）' },
  { char: '自', on: 'ジ・シ', kun: 'みずか(ら)', strokes: 6, category: 'sonota', example: '自分（じぶん）' },
  { char: '船', on: 'セン', kun: 'ふね・ふな', strokes: 11, category: 'sonota', example: '船（ふね）' },
  { char: '組', on: 'ソ', kun: 'く(む)・くみ', strokes: 11, category: 'sonota', example: '組（くみ）' },
  { char: '電', on: 'デン', kun: '', strokes: 13, category: 'sonota', example: '電気（でんき）' },
  { char: '東', on: 'トウ', kun: 'ひがし', strokes: 8, category: 'sonota', example: '東（ひがし）' },
  { char: '西', on: 'セイ・サイ', kun: 'にし', strokes: 6, category: 'sonota', example: '西（にし）' },
  { char: '南', on: 'ナン・ナ', kun: 'みなみ', strokes: 9, category: 'sonota', example: '南（みなみ）' },
  { char: '北', on: 'ホク', kun: 'きた', strokes: 5, category: 'sonota', example: '北（きた）' },
  { char: '明', on: 'メイ・ミョウ', kun: 'あか(るい)・あ(ける)', strokes: 8, category: 'sonota', example: '明るい（あかるい）' },
  { char: '里', on: 'リ', kun: 'さと', strokes: 7, category: 'sonota', example: '里（さと）' },
  { char: '理', on: 'リ', kun: '', strokes: 11, category: 'sonota', example: '理科（りか）' },
  { char: '分', on: 'ブン・フン・ブ', kun: 'わ(ける)・わ(かる)', strokes: 4, category: 'sonota', example: '分ける（わける）' },
];
